[package]
name = "wonremote-viewer"
version = "0.1.55"
description = "WonRemote Viewer desktop shell"
authors = ["WonRemote"]
edition = "2021"

[lib]
name = "wonremote_viewer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
winreg = "0.52"
windows-sys = { version = "0.59", features = [
    "Win32_System_JobObjects",
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi"
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22"

[features]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
opt-level = "s"
codegen-units = 16
lto = false
debug = false
strip = "debuginfo"
